name: MongoDB and Selenium Integration Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mongodb-integration-tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017

    env:
      MONGO_URI: "mongodb://localhost:27017/"  # MongoDB URI
      MONGO_DB: "sampleupload"                  # Database name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html pymongo selenium

      - name: List all files
        run: find . -type f

      - name: Wait for MongoDB to be ready
        run: |
          until nc -zv localhost 27017; do
            echo "Waiting for MongoDB to start..."
            sleep 1
          done
          echo "MongoDB is ready"

      

      

      - name: Seed MongoDB
        run: python app/seed.py

      - name: Test listing entries
        run: python app/app.py
        

      - name: Set Timezone to IST
        run: sudo timedatectl set-timezone Asia/Kolkata

      - name: Set up ChromeDriver and Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Run Selenium tests and generate report
        id: selenium_tests
        run: |
          pytest --html=selenium-report.html --self-contained-html > selenium_results.log || true
          cat selenium_results.log


      